
trigger: none

pool:
  vmImage: 'ubuntu-latest'

variables:
  tag: 'azuredevops-$(Build.BuildNumber)'
  imageName: 'mikebroomfield/azure-snake-dockle'
  
stages:

  - stage: Build & Scan
    jobs:
    - job: 
      steps:
      - task: Docker@2
        inputs:
          repository: 'mikebroomfield/azure-snake-dockle'
          command: 'build'
          Dockerfile: '**/Dockerfile'
          tags: '$(tag)'  
      - template: dockle-container.yml
        parameters:
          image: $(imageName):$(tag)  

