
trigger: none

pool:
  vmImage: 'ubuntu-latest'

variables:
  tag: 'azuredevops-$(Build.BuildNumber)'
  
stages:

  - stage: build
    jobs:
    - job: Build_Docker_Image
      pool:
        vmImage: 'ubuntu-latest'
      steps:
      - task: Docker@2
        inputs:
          command: 'build'
          Dockerfile: '**/Dockerfile'
          tags: '$(tag)'
      - template: dockle-container.yml
        parameters:
          image: $(tag)      -     



