
trigger: none

pool:
  vmImage: 'ubuntu-latest'

stages:

  - stage: build
    jobs:
    - job: Build_Docker_Image
      pool:
        vmImage: 'ubuntu-latest'
      steps:
      - task: Docker@2
        inputs:
          command: 'build'
          Dockerfile: '**/Dockerfile'


  - stage: scan
    jobs:
    - job: Security_Scans
      pool:
        vmImage: 'ubuntu-latest'
      steps:
      - template: dockle-container.yml
        parameters:
          image: $(Build.BuildId)
